version: "3.8"

services:
  mariadb:
    container_name: leek_db
    hostname: leek_db
    image: mariadb:10.10.2-jammy
    restart: always
    env_file:
      - .env

  bot:
    container_name: leek_bot
    hostname: leek_bot
    image: leekbot
    build: .
    environment:
      SQL_HOST: leek_db
      SQL_USER: ${MARIADB_USER}
      SQL_PASSWORD: ${MARIADB_PASSWORD}
      SQL_DB: leek
    env_file:
      - .env
