version: "3.8"

services:
  db:
    image: mariadb:10.10.2-jammy
    hostname: db
    restart: always
    env_file:
      - .env

  bot:
    image: leekbot
    build: .
    environment:
      SQL_HOST: db
      SQL_USER: ${MARIADB_USER}
      SQL_PASSWORD: ${MARIADB_PASSWORD}
      SQL_DB: leek
    env_file:
      - .env
