name: Build Docker Image

on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker/build-push-action@v4
        with:
          context: .
